version: '3'
services:
  # db:
  #   container_name: db
  #   build: mysql/    #add
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - '3307:3306'
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  back:
    container_name: back
    build: 
      context: back/  
      args: 
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production"
    volumes:
      - ./back:/myapp
    ports:
      - "3000:3000" 
    # depends_on:
    #   - db
    stdin_open: true
    tty: true
  front:
    container_name: front
    build: 
      context: front/  
      args: 
        FRONT_STRIPE_PK: ${FRONT_STRIPE_PK}
    command: yarn start
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
      - NODE_ENV=production
    volumes:
      - ./front:/myapp
    ports:
      - 80:3000
      - 443:3000
    depends_on:
      - back
volumes:
  mysql-data:
    driver: local